### ISSUE TITLE
Install can download the same version multiple times

### ISSUE THREAD

**Issue by jdheyburn** [feniix/asdf-sops#6]
I see that there is logic to prepend `v` to the version number if it is before a version:

https://github.com/feniix/asdf-sops/blob/master/bin/install#L17

```
  if [[ ! (${version} =~ [1-3]\.[0-4]) ]]; then
    # version is greater than 3.4.0
    version="v${version}"
  fi
```

The install path does not respect this, as such you can have a scenario where the same version can be downloaded twice.

```
asdf install sops 3.6.0
asdf install sops v3.6.0

$ ls ~/.asdf/installs/sops/
3.6.0 v3.6.0
```

**Comment by feniix** [comment]
I think this was fixed

```
$ asdf list all sops
3.0.0
3.0.1
3.0.2
3.0.3
3.0.4
3.0.5
3.1.0
3.1.1
3.2.0
3.3.0
3.3.1
3.4.0
3.5.0
3.6.0
3.6.1
3.7.0
3.7.1
3.7.2
3.7.3
```
