### ISSUE TITLE
"asdf list all sops" does not work

### ISSUE THREAD

**Issue by yogeek** [feniix/asdf-sops#7]
Thanks for this plugin :+1: 
Unfortunately, the list versions does not seem to work.
Seems related to a github API rate limit on mozilla/sops repo... can you confirm ?
If this is the case, is it possible to return a user-friendly error in the `list-all` script please ?

**Comment by feniix** [comment]
```
$ asdf list all sops
3.0.0
3.0.1
3.0.2
3.0.3
3.0.4
3.0.5
3.1.0
3.1.1
3.2.0
3.3.0
3.3.1
3.4.0
3.5.0
3.6.0
3.6.1
3.7.0
3.7.1
3.7.2
3.7.3
```
